controller_manager:
  ros__parameters:
    update_rate: 60
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    # forward_velocity_controller:
    #   type: forward_command_controller/ForwardCommandController

    omni_wheel_drive_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

forward_velocity_controller:
  ros__parameters:
    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - br_wheel_joint
      - bl_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity

omni_wheel_drive_controller:
  ros__parameters:
    wheel_offset: 0.7853981633974485
    wheel_names:
      [
        "fl_wheel_joint",
        "bl_wheel_joint",
        "br_wheel_joint",
        "fr_wheel_joint",
      ]

    robot_radius: 0.252
    wheel_radius: 0.076

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    open_loop: true
    position_feedback: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
